version: "3.3"
services:
  sample:
    build: .
    volumes:
      - .:/src:rw
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_USERNAME=benefitServiceUser"
      - "DB_PASSWORD=myPassword"
      - "DB_DATABASE=benefit-service"
      - "NODE_ENV=development"
      - "SERVICE_NAME=sample"
      - "SERVER_PORT=9000"
      - "LOG_LEVEL=info"
      - "SHARED_SECRETS=['secret1', 'secret2']"
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:latest
    environment:
      - "MYSQL_USER=benefitServiceUser"
      - "MYSQL_PASSWORD=myPassword"
      - "MYSQL_RANDOM_ROOT_PASSWORD=true"
      - "MYSQL_DATABASE=benefit-service"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      start_period: 3s
      timeout: 2s
      retries: 10
